### ISSUE TITLE
必应每天可以提交多少个URL？

### ISSUE THREAD

**Issue by suyin-long** [cjh0613/hexo-submit-urls-to-search-engine#3]
刚才试用了一下，一下提交了200个URL，百度全部成功提交，但是必应好多都没有提交上去，好像是超出了每天提交的上限，所以想问一下必应每天提交的上限是多少？
谷歌的没有测试，因为没有梯子。。。

**Comment by cjh0613** [comment]
应该可以到必应新站长平台进行查询，这个是动态的，可能随时更改。另外你是手动把count设为200+，还是程序问题，提交200多个链接?

**Comment by cjh0613** [comment]
即https://www.bing.com/webmasters/submiturl?siteUrl=你的网站链接，目前只支持英文，可从老站长平台点击搜索词进入

**Comment by suyin-long** [comment]
> 应该可以到必应新站长平台进行查询，这个是动态的，可能随时更改。另外你是手动把计数设为200+，还是程序问题，提交200个多个链接？

我是手动设置的`count: 200`，把提交的数量设置为了200。
刚才我查了下，今天的必应的分配额是10。

**Comment by suyin-long** [comment]
另外，我发现百度提交虽然显示`Baidu response:  {"remain":2999,"success":1}`，表示提交成功，但是去站长平台看数据后却发现
没有数据，如图：
![1](https://user-images.githubusercontent.com/49554285/87121834-470b9800-c2b6-11ea-8c00-a4cf151cf2d8.png)

**Comment by cjh0613** [comment]
是的

**Comment by cjh0613** [comment]
![image](https://user-images.githubusercontent.com/25498029/87122008-95209b80-c2b6-11ea-816f-7e9299c2655c.png)

**Comment by cjh0613** [comment]
这句话有歧义，我等会改一下

**Comment by cjh0613** [comment]
您在第`t+2`天才可以看到第`t`天的推送链接数。这下够准确了。

**Comment by suyin-long** [comment]
> 您在第`t+2`天才可以看到第`t`天的推送链接数。这下够准确了。

也就是说百度提交的当天看不到，要过1-2天才能看到；
而必应提交的在提交后即可查到，对吧！

**Comment by cjh0613** [comment]
是的

**Comment by suyin-long** [comment]
> 是的

明白了，多谢解惑，给你个star！

**Comment by cjh0613** [comment]
收到！有兴趣可以换个友链，本站说明：https://cjh0613.github.io/blog/friends/index.html

**Comment by suyin-long** [comment]
> 收到！有兴趣可以换个友链，本站说明：[https](https://cjh0613.github.io/blog/friends/index.html) ://cjh0613.github.io/blog/friends/index.html[](https://cjh0613.github.io/blog/friends/index.html)

我不知道你那友链怎么弄。。。
我博客地址：https://suyin-blog.club/

**Comment by cjh0613** [comment]
好，我写的说明太复杂了，回头改一下。就在这里加一下我的站点即可
![image](https://user-images.githubusercontent.com/25498029/87126948-ac17bb80-c2bf-11ea-8030-ec0fed03db8d.png)

你的站点信息我已添加至全站页脚及朋友页面。

**Comment by cjh0613** [comment]
峡州仙士之页   https://cjh0613.github.io/blog/index.html

**Comment by suyin-long** [comment]
> 好，我写的说明太复杂了，回头改一下。就在这里加一下我的站点即可
> ![图片](https://user-images.githubusercontent.com/25498029/87126948-ac17bb80-c2bf-11ea-8030-ec0fed03db8d.png)
> 
> 您的站点信息我已添加至全站页脚及朋友页面。

明白了，好说！

**Comment by cjh0613** [comment]
对

**Comment by suyin-long** [comment]
已经添加友链，如图：
| |
suyin_long
|
|
suyin_long@163.com
|
签名由网易邮箱大师定制
在2020年7月10日 15:50，峡州仙士<notifications@github.com> 写道：

Closed #3.
