### ISSUE TITLE
[报告问题] 推送链接到Bing上之后，还是搜不到文章

### ISSUE THREAD

**Issue by XiaotaoGuo** [cjh0613/hexo-submit-urls-to-search-engine#5]
你好，我根据你的教程之后设置了baidu和bing的推送，bing显示推送成功了，而且在网站上也能看到推送记录。但是无论是搜索`site:网址`或者直接搜索博客标题/内容还是搜不到，请问这个情况正常吗？目前大概隔了十几个小时，谢谢！

**Comment by cjh0613** [comment]
新站的话，索引量 0→1 需要的时间可能很长，也许一个月……请耐心等待

**Comment by cjh0613** [comment]
已在文档中添加此提示
